variables:
  System.Debug: true

jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: Ubuntu-latest
    steps:
      - task: UseDotNet@2
        displayName: Use .NET Core Runtime 2.1.x (For SonarCloud)
        inputs:
          packageType: runtime
          version: 2.1.x

      - task: UseDotNet@2
        displayName: Use .NET Core SDK 5.0.x
        inputs:
          packageType: sdk
          version: 5.0.x

      - task: SonarCloudPrepare@1
        displayName: Prepare SonarCloud Analysis
        inputs:
          SonarCloud: SonarCloud
          organization: xxxxxxxxxxxxxxx
          scannerMode: MSBuild
          projectKey: xxxxxxxxxxxxxxx
          projectName: xxxxxxxxxxxxxxx


      - task: DotNetCoreCLI@2
        displayName: Restore Packages
        inputs:
          command: restore
          projects: $(Build.SourcesDirectory)/SonarBuildFailRepro.sln

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          arguments: --no-restore --configuration Release --verbosity normal
          projects: $(Build.SourcesDirectory)/SonarBuildFailRepro.sln
